model_categories:
  binary_classification_base:
    data_types:
      string: TEXT
      categorical: CATEGORICAL
      numeric: NUMERIC

    field_use_types:
      id: ID
      input: INPUT
      target: TARGET

    schemaFields:
      fieldName: field_name
      dataType: data_type
      fieldUseType: field_use_type

    datasets:
      cancer:
        fname: cancer_schema_cfg.csv
        targetClass: M
      credit_card:
        fname: credit_card_schema_cfg.csv
        targetClass: negative
      electrical_grid:
        fname: electrical_grid_schema_cfg.csv
        targetClass: unstable
      employee_attrition:
        fname: employee_attrition_schema_cfg.csv
        targetClass: 1
      mushroom:
        fname: mushroom_schema_cfg.csv
        targetClass: p
      nba:
        fname: nba_schema_cfg.csv
        targetClass: 1
      segment:
        fname: segment_schema_cfg.csv
        targetClass: P
      spam:
        fname: spam_schema_cfg.csv
        targetClass: 1
      telco_churn:
        fname: telco_churn_schema_cfg.csv
        targetClass: "Yes"
      titanic:
        fname: titanic_schema_cfg.csv
        targetClass: 1
